name: divinitaion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  intl: ^0.18.0

  screenshot: ^3.0.0
  share_plus: ^10.1.2
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.0.0
  image_picker: ^0.8.7+3
  file_picker: ^5.3.0

flutter:
  uses-material-design: true

  # Assets bölümünü aktif hale getiriyoruz.
  assets:
    - lib/assets/logo1.png 
    - lib/assets/kahvefali.png 
    - lib/assets/tarot.png
    - lib/assets/hand.png 
    - lib/assets/dharita.png
    - lib/assets/fonts/PlaywriteGBS-Italic.ttf # Font dosyasını ekleyin
    - lib/assets/background.png 
    - lib/assets/tarot_karti.jpg 

  fonts:
    - family: PlaywriteGBS
      fonts:
        - asset: lib/assets/fonts/PlaywriteGBS-Italic.ttf # Font ailesini tanımlayın
