// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDGDB1uJ5CpJFqPoNY_0uofHN9zV4dgc',
    appId: '1:667616866182:web:302eff5783d0640bd50607',
    messagingSenderId: '667616866182',
    projectId: 'fallinfal-38d40',
    authDomain: 'fallinfal-38d40.firebaseapp.com',
    storageBucket: 'fallinfal-38d40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkrvItCJP1tfbaistWO9Da50bKrDXCZs',
    appId: '1:667616866182:android:08fbba8ffc104ecfd50607',
    messagingSenderId: '667616866182',
    projectId: 'fallinfal-38d40',
    storageBucket: 'fallinfal-38d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-MlGOUqtBbaenw5wE6haQJ2za3nianI',
    appId: '1:667616866182:ios:f9af819466bbaf2ed50607',
    messagingSenderId: '667616866182',
    projectId: 'fallinfal-38d40',
    storageBucket: 'fallinfal-38d40.firebasestorage.app',
    iosClientId: '667616866182-th2pn4k0ckd364b996r3b9j6e8ks5brh.apps.googleusercontent.com',
    iosBundleId: 'com.example.divinitaion',
  );

}